### PR TITLE
Replaced render(controller...) by twig extension to improve performances

### PR DESCRIPTION
**Pull request by GWillmann**
According to several articles : [here (French)](https://www.baptiste-donaux.fr/twig-render-controller-le-faux-bon-ami/) and [here (English)](https://tideways.io/profiler/blog/5-ways-to-optimize-symfony-baseline-performance), using render(controller) degrades performances.

I replaced both render(controller) by a twig extension : GAExtension.

I also cleaned up the code by removing unnecessary files.

Thanks.

### CODE REVIEW

**Comment by GWillmann** [comment]
ping @hamaryuginh :) What do you think about it?

**Comment by hamaryuginh** [comment]
I haven't yet had time to look your pull request. Maybe this week-end...

**Comment by GWillmann** [comment]
Sorry to bother you again @hamaryuginh :/ could you take a look at the pull request please?

**Comment by hamaryuginh** [comment]
Sorry for the delay ;)

**Pull request merged**
